#!/bin/bash

while [ $# -gt 0 ]; do
	case "$1" in
		"--print-path"|"-p")
			echo /opt/Xcode.app/Contents/Developer/
			exit 0
			;;

		*)
			echo "Unrecognized option: $1"
			exit 1
			;;
	esac
	shift
done
